### ISSUE TITLE
Enable Dashboard for npm

### ISSUE THREAD

**Issue by Puffo19** [crowdsecurity/example-docker-compose#12]
Hello, 

would it be possible to enable the dashboard from crowedsec? 

I added 
```
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
```
to the docker-compose file from https://github.com/crowdsecurity/example-docker-compose/blob/main/npm/docker-compose.yml 

Then I tried to get the dashboard setup: 
```
cscli dashboard setup
? CrowdSec takes no responsibility for the security of your metabase instance. Do you accept these responsibilities ? Yes
? For metabase docker to be able to access SQLite file we need to add a new group called 'crowdsec' to the system, is it ok for you ? Yes
FATA[26-11-2023 15:46:02] unable to find 'groupadd' command, can't continue 
```

Trying to do `groupadd crowdsec` brings me a little step forward. But I get still an fatal error which I can't solve:
```
cscli dashboard setup
? CrowdSec takes no responsibility for the security of your metabase instance. Do you accept these responsibilities ? Yes
INFO[26-11-2023 15:46:52] /var/lib/crowdsec/data/metabase.db exists, skip. 
INFO[26-11-2023 15:46:52] Pulling docker image metabase/metabase:v0.46.6.1 
...
INFO[26-11-2023 15:46:53] creating container 'crowdsec-metabase'       
FATA[26-11-2023 15:46:53] container create: failed to create container : Error response from daemon: invalid mount config for type "bind": bind source path does not exist: /var/lib/crowdsec/data
```

the folder exists `/var/lib/crowdsec/data` in the docker container. 
What can solve this problem?

**Comment by LaurenceJJones** [comment]
Running `cscli dashboard setup` from within the container is not supported. You can see how to run a separate image from the basic example https://github.com/crowdsecurity/example-docker-compose/blob/main/basic/docker-compose.yml

**Comment by Puffo19** [comment]
Thanks a lot. Thats helps me for the next steps.
