### ISSUE TITLE
no arm64 crowdsec docker image but only amd64

### ISSUE THREAD

**Issue by erdoukki** [crowdsecurity/example-docker-compose#4]
https://discourse.crowdsec.net/t/crowdsec-docker-amd64-only/313

**Comment by erdoukki** [comment]
https://github.com/crowdsecurity/crowdsec/issues/1014
```
root@STARGATE:~/CS/example-docker-compose# docker image ls
REPOSITORY                 TAG           IMAGE ID       CREATED             SIZE
crowdsecurity/crowdsec     v1.2.0        2a8f750164f3   4 weeks ago         158MB
```
STEP 1 : OK
STEP 2 : KO
```
Step 2/2 : RUN mkdir /data/ && wget https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/metabase_sqlite.zip && unzip metabase_sqlite.zip -d /data/
 ---> [Warning] The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
 ---> Running in 1a80e95d8c35
standard_init_linux.go:228: exec user process caused: exec format error
The command '/bin/sh -c mkdir /data/ && wget https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/metabase_sqlite.zip && unzip metabase_sqlite.zip -d /data/' returned a non-zero code: 1
ERROR: Service 'dashboard' failed to build
```

**Comment by erdoukki** [comment]
The problem is from metabase image (amd64 only) ... will look at this !

**Comment by alexceee** [comment]
Same here, is there a fix for the above crash on file not found errors?

**Comment by mmetc** [comment]
Hi @alexceee ,

I can't replicate.
How did you run it?
It's even better if you can provide details on a separate issue because this has nothing to do with arm64 now

**Comment by ApolloF** [comment]
I made [this](https://hub.docker.com/r/apollof/crowdsec_metabase) Metabase arm64/amd64 image with the crowdsec dashboard integrated if anyone wants it.

**Comment by tokar86a** [comment]
> I made [this](https://hub.docker.com/r/apollof/crowdsec_metabase) Metabase arm64/amd64 image with the crowdsec dashboard integrated if anyone wants it.

I try to run it but it dont seems to be able to run the database.

**Comment by ApolloF** [comment]
> > I made [this](https://hub.docker.com/r/apollof/crowdsec_metabase) Metabase arm64/amd64 image with the crowdsec dashboard integrated if anyone wants it.
> 
> I try to run it but it dont seems to be able to run the database.

Which tag are you using?

**Comment by LaurenceJJones** [comment]
Closing issue since metabase doesnt directly support arm64, so user has to rely on non official images
