### ISSUE TITLE
dashboard metabase cant build

### ISSUE THREAD

**Issue by alf149** [crowdsecurity/example-docker-compose#6]
On Ubuntu VERSION="20.04.2
from a clean server with docker and docker-compose installed
I get errors on dashboard metabase build. 

Step 1/2 : FROM metabase/metabase
latest: Pulling from metabase/metabase
a0d0a0d46f8b: Already exists
c4f0e81aa109: Pull complete
b83db16da127: Pull complete
8f729421eec7: Pull complete
51774aa4d406: Pull complete
Digest: sha256:8bb67290f5838de763f124b2663d09453e5dbfae1ef15a080d28f3ca76d3e39e
Status: Downloaded newer image for metabase/metabase:latest
 ---> b2dcf4f4176c
Step 2/2 : RUN mkdir /data/ && wget https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/metabase_sqlite.zip && unzip metabase_sqlite.zip -d /data/
 ---> Running in 0c9ce4fbc2bd
wget: bad address 'crowdsec-statics-assets.s3-eu-west-1.amazonaws.com'
ERROR: Service 'dashboard' failed to build: The command '/bin/sh -c mkdir /data/ && wget https://crowdsec-statics-assets.s3-eu-west-1.amazonaws.com/metabase_sqlite.zip && unzip metabase_sqlite.zip -d /data/' returned a non-zero code: 1

**Comment by LaurenceJJones** [comment]
If this is still an issue please open an issue on the main CrowdSec repository as this repository is held for examples rather than support.
